name: "u-timehollyname"

filebeat.inputs:
  - type: filestream
    id: xray-access
    enabled: true
    paths:
      - /var/log/app/xray-access.log
    fields:
      app: xray-access
    fields_under_root: true
    prospector.scanner.fingerprint.enabled: false
    file_identity.native: ~

  - type: filestream
    id: xray-connections
    enabled: true
    paths:
      - /var/log/app/connections.log
    fields:
      app: xray-connections
    fields_under_root: true
    prospector.scanner.fingerprint.enabled: false
    file_identity.native: ~

output.logstash:
  hosts: ["xrayelk.dev-dom.oraclesiebelcrm.com:5044"]

logging.level: info
logging.to_stderr: true