name: "${FILEBEAT_NAME}"

logging.level: ${FILEBEAT_LOGGING_LEVEL}
logging.to_stderr: true

output.logstash:
  hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]

filebeat.inputs:
  - type: filestream
    id: xray-access
    enabled: true
    paths:
      - /var/log/remnanode/access.log
    fields:
      app: xray-access
    fields_under_root: true
    prospector.scanner.fingerprint.enabled: false
    file_identity.native: ~

  - type: filestream
    id: xray-connections
    enabled: true
    paths:
      - /var/log/snitch/connections.log
    fields:
      app: xray-connections
    fields_under_root: true
    prospector.scanner.fingerprint.enabled: false
    file_identity.native: ~
