services:
  python:
    tty: true
    image: python:3.11.14-alpine3.23
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./snitch:/snitch
    command: >
      sh -c "python /snitch/main.py"
