services:
  remnanode:
    image: remnawave/node:latest
    restart: unless-stopped
    hostname: remnanode
    container_name: remnanode
    network_mode: host
    env_file: ./remnanode/.env
    volumes:
      - ./remnanode/volume:/var/log/xray
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576

  snitch:
    build: ./snitch
    restart: unless-stopped
    hostname: snitch
    container_name: snitch
    network_mode: host
    env_file: ./snitch/.env
    command: >
      sh -c "python main.py"
    volumes:
      - ./snitch:/snitch
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - remnanode

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.3.0
    restart: unless-stopped
    container_name: filebeat
    volumes:
      - ./filebeat/volume:/usr/share/filebeat/data
      - ./filebeat/configuration.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./remnanode/volume/access.log:/var/log/app/xray-access.log:ro
      - ./snitch/volume/connections.log:/var/log/app/connections.log:ro
    depends_on:
      - remnanode
